# -*- python -*-
import re
Import("env")

env.CheckSwig("python", ilang="c++", includedProducts="solvetansip afw utils daf_base pex_exceptions pex_policy daf_persistence pex_logging daf_data security")
env.LoadableModuleIncomplete("_tansip", Split("WCS_TANSIPLib.i"),
                             CCFLAGS=re.sub("-Wall", "", " ".join(env['CCFLAGS'])),
                             LIBS=env.getlibs("solvetansip"))
