#!/usr/bin/env python
import lsst.pex.policy as pexPolicy

import hsc.meas.tansip.WCS_CHECK as WCS_CHECK
def F_WCS_CHECK_CCDPOSITION_SC(NUMBER,APROP,CPROP):
    print "F_WCS_CHECK_CCDPOSITION_SC PY"
    WCS_CHECK.F_WCS_CHECK_CCDPOSITION_SC(NUMBER,APROP,CPROP)

def F_WCS_CHECK_OADISTORTION_SC(NUMBER,ANGLE,APROP,CPROP,CSIP):
    print "F_WCS_CHECK_OADISTORTION_SC PY"
    WCS_CHECK.F_WCS_CHECK_OADISTORTION_SC(NUMBER,ANGLE,APROP,CPROP,CSIP)

def F_WCS_CHECK_OAPOSITION_SC(NUMBER,APROP,CPROP,CSIP):
    print "F_WCS_CHECK_OAPOSITION_SC PY"
    WCS_CHECK.F_WCS_CHECK_OAPOSITION_SC(NUMBER,APROP,CPROP,CSIP)
