#!/usr/bin/env python
#--------------------------------------------------
#solvetansip.py
#
#Last Update 2013/03/01
#--------------------------------------------------

import os, sys
import os.path
import SLVTANSIP.SLVTANSIP_SWIG as SLVTANSIP_SWIG
import SLVTANSIP.SLVTANSIP_TOOL as SLVTANSIP_TOOL

def main(ccdfitsdir,objfitsdir): 
	print "--- solvetansip_file.py START ---"
	ANA=SLVTANSIP_SWIG.SLVTANSIP_SWIG_MAKE_ANAfromfits(ccdfitsdir);

	CCDNUM=SLVTANSIP_SWIG.SLVTANSIP_SWIG_GET_CCDNUM(ANA);
	print CCDNUM
#	MAXR =SLVTANSIP_SWIG.SLVTANSIP_SWIG_GET_MAXR  (ANA);
#	print MAXR
#	CRPIX=SLVTANSIP_SWIG.SLVTANSIP_SWIG_GET_CRPIX (ANA, 0);
#	print CRPIX[0],CRPIX[1]
#	CRPIX=SLVTANSIP_SWIG.SLVTANSIP_SWIG_GET_CRPIX (ANA,-1);
#	print CRPIX[0],CRPIX[1]
#	CRVAL=SLVTANSIP_SWIG.SLVTANSIP_SWIG_GET_CRVAL (ANA, 0);
#	print CRVAL[0],CRVAL[1]
#	CRVAL=SLVTANSIP_SWIG.SLVTANSIP_SWIG_GET_CRVAL (ANA,-1);
#	print CRVAL[0],CRVAL[1]
#	CORNAR=SLVTANSIP_SWIG.SLVTANSIP_SWIG_GET_CORNAR_GLOBAL(ANA)
#	print  CORNAR[ 0][0],CORNAR[ 0][1]
#	print CORNAR[ 1][0],CORNAR[ 1][1]
#	print CORNAR[ 2][0],CORNAR[ 2][1]
#	print CORNAR[ 3][0],CORNAR[ 3][1]
	GPOS=SLVTANSIP_SWIG.SLVTANSIP_SWIG_GET_GPOS_GLOBAL(ANA)
	GPOSDIR=ccdfitsdir+"/GPOS.dat"
	Gout = open(GPOSDIR,"w")
	for CID in range(CCDNUM): 
		print >> Gout, GPOS[CID][0],GPOS[CID][1],GPOS[CID][2]
#	SLVTANSIP_TOOL.SHOW_CCDPOSITION_GLOBAL(ANA,  0,1,1,1)
#	SLVTANSIP_TOOL.SHOW_CCDPOSITION_GLOBAL(ANA, -1,1,1,1)
#	SLVTANSIP_TOOL.SHOW_CCDPOSITION_RADEC (ANA,  0,1,1,1)
#	SLVTANSIP_TOOL.SHOW_CCDPOSITION_RADEC (ANA, -1,1,1,1)
	CID=-1
	OBJFLAG=1
	OUTFLAG=0
	EPSFLAG=1
	PNGFLAG=1
	SLVTANSIP_TOOL.SHOW_OBJPOSITION_GLOBAL(ANA,objfitsdir,OBJFLAG,CID,OUTFLAG,EPSFLAG,PNGFLAG)
	SLVTANSIP_TOOL.SHOW_OBJPOSITION_RADEC (ANA,objfitsdir,OBJFLAG,CID,OUTFLAG,EPSFLAG,PNGFLAG)
#	SLVTANSIP_TOOL.SHOW_OBJPOSITION_RADEC (ANA,objfitsdir,OBJFLAG,CID,OUTFLAG,EPSFLAG,PNGFLAG)
#	SLVTANSIP_TOOL.SHOW_OBJPOSITION_GLOBAL(ANA,objfitsdir,OBJFLAG,CID,OUTFLAG,EPSFLAG,PNGFLAG)
#	SLVTANSIP_TOOL.SHOW_OBJPOSITION_RADEC (ANA,objfitsdir,OBJFLAG,CID,OUTFLAG,EPSFLAG,PNGFLAG)
#	SLVTANSIP_TOOL.SHOW_OBJPOSITION_GLOBAL(ANA,objfitsdir,OBJFLAG,CID,OUTFLAG,EPSFLAG,PNGFLAG)
#	SLVTANSIP_TOOL.SHOW_OBJPOSITION_RADEC (ANA,objfitsdir,OBJFLAG,CID,OUTFLAG,EPSFLAG,PNGFLAG)
#	SLVTANSIP_TOOL.SHOW_OBJPOSITION_RADEC (ANA,objfitsdir,OBJFLAG,CID,OUTFLAG,EPSFLAG,PNGFLAG)
#	SLVTANSIP_TOOL.SHOW_OBJPOSITION_GLOBAL(ANA,objfitsdir,OBJFLAG,CID,OUTFLAG,EPSFLAG,PNGFLAG)
	CID=-1
	SLVTANSIP_TOOL.SHOW_OBJDISTORTION_GLOBAL(ANA,objfitsdir,OBJFLAG,CID,OUTFLAG,EPSFLAG,PNGFLAG)
#	SLVTANSIP_TOOL.SHOW_DENSITY(ANA,0,1,1,1)


	SLVTANSIP_SWIG.SLVTANSIP_SWIG_DEL_ANAfromfits(ANA)
	print "--- solvetansip_file.py END ---"

if __name__ == '__main__':

    ccdfits = sys.argv[1]
    objfits = sys.argv[2]
    main(ccdfits,objfits)
