# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.4
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_SLVTS_SWIG', [dirname(__file__)])
        except ImportError:
            import _SLVTS_SWIG
            return _SLVTS_SWIG
        if fp is not None:
            try:
                _mod = imp.load_module('_SLVTS_SWIG', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _SLVTS_SWIG = swig_import_helper()
    del swig_import_helper
else:
    import _SLVTS_SWIG
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _SLVTS_SWIG.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _SLVTS_SWIG.SwigPyIterator_value(self)
    def incr(self, n = 1): return _SLVTS_SWIG.SwigPyIterator_incr(self, n)
    def decr(self, n = 1): return _SLVTS_SWIG.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _SLVTS_SWIG.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _SLVTS_SWIG.SwigPyIterator_equal(self, *args)
    def copy(self): return _SLVTS_SWIG.SwigPyIterator_copy(self)
    def next(self): return _SLVTS_SWIG.SwigPyIterator_next(self)
    def __next__(self): return _SLVTS_SWIG.SwigPyIterator___next__(self)
    def previous(self): return _SLVTS_SWIG.SwigPyIterator_previous(self)
    def advance(self, *args): return _SLVTS_SWIG.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _SLVTS_SWIG.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _SLVTS_SWIG.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _SLVTS_SWIG.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _SLVTS_SWIG.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _SLVTS_SWIG.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _SLVTS_SWIG.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _SLVTS_SWIG.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class VS(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VS, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VS, name)
    __repr__ = _swig_repr
    def iterator(self): return _SLVTS_SWIG.VS_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _SLVTS_SWIG.VS___nonzero__(self)
    def __bool__(self): return _SLVTS_SWIG.VS___bool__(self)
    def __len__(self): return _SLVTS_SWIG.VS___len__(self)
    def pop(self): return _SLVTS_SWIG.VS_pop(self)
    def __getslice__(self, *args): return _SLVTS_SWIG.VS___getslice__(self, *args)
    def __setslice__(self, *args): return _SLVTS_SWIG.VS___setslice__(self, *args)
    def __delslice__(self, *args): return _SLVTS_SWIG.VS___delslice__(self, *args)
    def __delitem__(self, *args): return _SLVTS_SWIG.VS___delitem__(self, *args)
    def __getitem__(self, *args): return _SLVTS_SWIG.VS___getitem__(self, *args)
    def __setitem__(self, *args): return _SLVTS_SWIG.VS___setitem__(self, *args)
    def append(self, *args): return _SLVTS_SWIG.VS_append(self, *args)
    def empty(self): return _SLVTS_SWIG.VS_empty(self)
    def size(self): return _SLVTS_SWIG.VS_size(self)
    def clear(self): return _SLVTS_SWIG.VS_clear(self)
    def swap(self, *args): return _SLVTS_SWIG.VS_swap(self, *args)
    def get_allocator(self): return _SLVTS_SWIG.VS_get_allocator(self)
    def begin(self): return _SLVTS_SWIG.VS_begin(self)
    def end(self): return _SLVTS_SWIG.VS_end(self)
    def rbegin(self): return _SLVTS_SWIG.VS_rbegin(self)
    def rend(self): return _SLVTS_SWIG.VS_rend(self)
    def pop_back(self): return _SLVTS_SWIG.VS_pop_back(self)
    def erase(self, *args): return _SLVTS_SWIG.VS_erase(self, *args)
    def __init__(self, *args): 
        this = _SLVTS_SWIG.new_VS(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _SLVTS_SWIG.VS_push_back(self, *args)
    def front(self): return _SLVTS_SWIG.VS_front(self)
    def back(self): return _SLVTS_SWIG.VS_back(self)
    def assign(self, *args): return _SLVTS_SWIG.VS_assign(self, *args)
    def resize(self, *args): return _SLVTS_SWIG.VS_resize(self, *args)
    def insert(self, *args): return _SLVTS_SWIG.VS_insert(self, *args)
    def reserve(self, *args): return _SLVTS_SWIG.VS_reserve(self, *args)
    def capacity(self): return _SLVTS_SWIG.VS_capacity(self)
    __swig_destroy__ = _SLVTS_SWIG.delete_VS
    __del__ = lambda self : None;
VS_swigregister = _SLVTS_SWIG.VS_swigregister
VS_swigregister(VS)

class VVS(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VVS, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VVS, name)
    __repr__ = _swig_repr
    def iterator(self): return _SLVTS_SWIG.VVS_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _SLVTS_SWIG.VVS___nonzero__(self)
    def __bool__(self): return _SLVTS_SWIG.VVS___bool__(self)
    def __len__(self): return _SLVTS_SWIG.VVS___len__(self)
    def pop(self): return _SLVTS_SWIG.VVS_pop(self)
    def __getslice__(self, *args): return _SLVTS_SWIG.VVS___getslice__(self, *args)
    def __setslice__(self, *args): return _SLVTS_SWIG.VVS___setslice__(self, *args)
    def __delslice__(self, *args): return _SLVTS_SWIG.VVS___delslice__(self, *args)
    def __delitem__(self, *args): return _SLVTS_SWIG.VVS___delitem__(self, *args)
    def __getitem__(self, *args): return _SLVTS_SWIG.VVS___getitem__(self, *args)
    def __setitem__(self, *args): return _SLVTS_SWIG.VVS___setitem__(self, *args)
    def append(self, *args): return _SLVTS_SWIG.VVS_append(self, *args)
    def empty(self): return _SLVTS_SWIG.VVS_empty(self)
    def size(self): return _SLVTS_SWIG.VVS_size(self)
    def clear(self): return _SLVTS_SWIG.VVS_clear(self)
    def swap(self, *args): return _SLVTS_SWIG.VVS_swap(self, *args)
    def get_allocator(self): return _SLVTS_SWIG.VVS_get_allocator(self)
    def begin(self): return _SLVTS_SWIG.VVS_begin(self)
    def end(self): return _SLVTS_SWIG.VVS_end(self)
    def rbegin(self): return _SLVTS_SWIG.VVS_rbegin(self)
    def rend(self): return _SLVTS_SWIG.VVS_rend(self)
    def pop_back(self): return _SLVTS_SWIG.VVS_pop_back(self)
    def erase(self, *args): return _SLVTS_SWIG.VVS_erase(self, *args)
    def __init__(self, *args): 
        this = _SLVTS_SWIG.new_VVS(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _SLVTS_SWIG.VVS_push_back(self, *args)
    def front(self): return _SLVTS_SWIG.VVS_front(self)
    def back(self): return _SLVTS_SWIG.VVS_back(self)
    def assign(self, *args): return _SLVTS_SWIG.VVS_assign(self, *args)
    def resize(self, *args): return _SLVTS_SWIG.VVS_resize(self, *args)
    def insert(self, *args): return _SLVTS_SWIG.VVS_insert(self, *args)
    def reserve(self, *args): return _SLVTS_SWIG.VVS_reserve(self, *args)
    def capacity(self): return _SLVTS_SWIG.VVS_capacity(self)
    __swig_destroy__ = _SLVTS_SWIG.delete_VVS
    __del__ = lambda self : None;
VVS_swigregister = _SLVTS_SWIG.VVS_swigregister
VVS_swigregister(VVS)

class VVVS(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VVVS, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VVVS, name)
    __repr__ = _swig_repr
    def iterator(self): return _SLVTS_SWIG.VVVS_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _SLVTS_SWIG.VVVS___nonzero__(self)
    def __bool__(self): return _SLVTS_SWIG.VVVS___bool__(self)
    def __len__(self): return _SLVTS_SWIG.VVVS___len__(self)
    def pop(self): return _SLVTS_SWIG.VVVS_pop(self)
    def __getslice__(self, *args): return _SLVTS_SWIG.VVVS___getslice__(self, *args)
    def __setslice__(self, *args): return _SLVTS_SWIG.VVVS___setslice__(self, *args)
    def __delslice__(self, *args): return _SLVTS_SWIG.VVVS___delslice__(self, *args)
    def __delitem__(self, *args): return _SLVTS_SWIG.VVVS___delitem__(self, *args)
    def __getitem__(self, *args): return _SLVTS_SWIG.VVVS___getitem__(self, *args)
    def __setitem__(self, *args): return _SLVTS_SWIG.VVVS___setitem__(self, *args)
    def append(self, *args): return _SLVTS_SWIG.VVVS_append(self, *args)
    def empty(self): return _SLVTS_SWIG.VVVS_empty(self)
    def size(self): return _SLVTS_SWIG.VVVS_size(self)
    def clear(self): return _SLVTS_SWIG.VVVS_clear(self)
    def swap(self, *args): return _SLVTS_SWIG.VVVS_swap(self, *args)
    def get_allocator(self): return _SLVTS_SWIG.VVVS_get_allocator(self)
    def begin(self): return _SLVTS_SWIG.VVVS_begin(self)
    def end(self): return _SLVTS_SWIG.VVVS_end(self)
    def rbegin(self): return _SLVTS_SWIG.VVVS_rbegin(self)
    def rend(self): return _SLVTS_SWIG.VVVS_rend(self)
    def pop_back(self): return _SLVTS_SWIG.VVVS_pop_back(self)
    def erase(self, *args): return _SLVTS_SWIG.VVVS_erase(self, *args)
    def __init__(self, *args): 
        this = _SLVTS_SWIG.new_VVVS(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _SLVTS_SWIG.VVVS_push_back(self, *args)
    def front(self): return _SLVTS_SWIG.VVVS_front(self)
    def back(self): return _SLVTS_SWIG.VVVS_back(self)
    def assign(self, *args): return _SLVTS_SWIG.VVVS_assign(self, *args)
    def resize(self, *args): return _SLVTS_SWIG.VVVS_resize(self, *args)
    def insert(self, *args): return _SLVTS_SWIG.VVVS_insert(self, *args)
    def reserve(self, *args): return _SLVTS_SWIG.VVVS_reserve(self, *args)
    def capacity(self): return _SLVTS_SWIG.VVVS_capacity(self)
    __swig_destroy__ = _SLVTS_SWIG.delete_VVVS
    __del__ = lambda self : None;
VVVS_swigregister = _SLVTS_SWIG.VVVS_swigregister
VVVS_swigregister(VVVS)

class VSLVTS(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VSLVTS, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VSLVTS, name)
    __repr__ = _swig_repr
    def iterator(self): return _SLVTS_SWIG.VSLVTS_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _SLVTS_SWIG.VSLVTS___nonzero__(self)
    def __bool__(self): return _SLVTS_SWIG.VSLVTS___bool__(self)
    def __len__(self): return _SLVTS_SWIG.VSLVTS___len__(self)
    def pop(self): return _SLVTS_SWIG.VSLVTS_pop(self)
    def __getslice__(self, *args): return _SLVTS_SWIG.VSLVTS___getslice__(self, *args)
    def __setslice__(self, *args): return _SLVTS_SWIG.VSLVTS___setslice__(self, *args)
    def __delslice__(self, *args): return _SLVTS_SWIG.VSLVTS___delslice__(self, *args)
    def __delitem__(self, *args): return _SLVTS_SWIG.VSLVTS___delitem__(self, *args)
    def __getitem__(self, *args): return _SLVTS_SWIG.VSLVTS___getitem__(self, *args)
    def __setitem__(self, *args): return _SLVTS_SWIG.VSLVTS___setitem__(self, *args)
    def append(self, *args): return _SLVTS_SWIG.VSLVTS_append(self, *args)
    def empty(self): return _SLVTS_SWIG.VSLVTS_empty(self)
    def size(self): return _SLVTS_SWIG.VSLVTS_size(self)
    def clear(self): return _SLVTS_SWIG.VSLVTS_clear(self)
    def swap(self, *args): return _SLVTS_SWIG.VSLVTS_swap(self, *args)
    def get_allocator(self): return _SLVTS_SWIG.VSLVTS_get_allocator(self)
    def begin(self): return _SLVTS_SWIG.VSLVTS_begin(self)
    def end(self): return _SLVTS_SWIG.VSLVTS_end(self)
    def rbegin(self): return _SLVTS_SWIG.VSLVTS_rbegin(self)
    def rend(self): return _SLVTS_SWIG.VSLVTS_rend(self)
    def pop_back(self): return _SLVTS_SWIG.VSLVTS_pop_back(self)
    def erase(self, *args): return _SLVTS_SWIG.VSLVTS_erase(self, *args)
    def __init__(self, *args): 
        this = _SLVTS_SWIG.new_VSLVTS(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _SLVTS_SWIG.VSLVTS_push_back(self, *args)
    def front(self): return _SLVTS_SWIG.VSLVTS_front(self)
    def back(self): return _SLVTS_SWIG.VSLVTS_back(self)
    def assign(self, *args): return _SLVTS_SWIG.VSLVTS_assign(self, *args)
    def resize(self, *args): return _SLVTS_SWIG.VSLVTS_resize(self, *args)
    def insert(self, *args): return _SLVTS_SWIG.VSLVTS_insert(self, *args)
    def reserve(self, *args): return _SLVTS_SWIG.VSLVTS_reserve(self, *args)
    def capacity(self): return _SLVTS_SWIG.VSLVTS_capacity(self)
    __swig_destroy__ = _SLVTS_SWIG.delete_VSLVTS
    __del__ = lambda self : None;
VSLVTS_swigregister = _SLVTS_SWIG.VSLVTS_swigregister
VSLVTS_swigregister(VSLVTS)


def SOLVETANSIP(*args):
  return _SLVTS_SWIG.SOLVETANSIP(*args)
SOLVETANSIP = _SLVTS_SWIG.SOLVETANSIP
# This file is compatible with both classic and new-style classes.


